name: Frontend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push de imagen
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: fabricioph2/frontend:latest

      - name: Instalar Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to Helm Registry
        env:
          HELM_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${HELM_REGISTRY_PASSWORD}" | helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Deploy files
        run: |
          sed -i "s|{{ version }}|${{ github.run_number }}|g" ./frontend/Chart.yaml
          cat ./frontend/Chart.yaml
          helm package ./frontend
 
          helm push ./frontend-${{ github.run_number }}.tgz oci://registry-1.docker.io/fabricioph2
